#!/bin/sh

icons="16"
icons="${icons} 24"
icons="${icons} 32"
icons="${icons} 48"
icons="${icons} 64"
icons="${icons} 96"
icons="${icons} 128"
icons="${icons} 256"
icons="${icons} 512"

cd /usr/lib/firebotv5

for icon in ${icons}; do
    xdg-icon-resource install --context mimetypes --size ${icon} resources/linux/firebotsetup-icon/${icon}x${icon}.png application-x-firebotsetup
done

xdg-mime install resources/linux/firebotsetup-mimetype.xml

update-desktop-database &> /dev/null