import Head from "next/head";

import favIcon from "assets/images/favicon.ico";

export default function Home() {
  return (
    <>
      <Head>
        <title>Firebot</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href={favIcon.src} />
      </Head>
      <div>Does fast reloading work?</div>
    </>
  );
}
