import Head from "next/head";

import favIcon from "assets/images/favIcon.ico";
import { PageWrapper } from "@/components/PageWrapper";
import { PageTitle } from "@/components/PageTitle";

export default function Home() {
  return (
    <>
      <Head>
        <title>Firebot</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href={favIcon.src} />
      </Head>
      <PageWrapper>
        <PageTitle title="Dashboard" />
        <div>Does fast reloading work?</div>
      </PageWrapper>
    </>
  );
}
