'use strict';

const path = require('path');
const fs = require('fs');

const REPO_ROOT = path.join(__dirname, '..');
const OUT_DIR = path.join(REPO_ROOT, 'dist', 'types');

module.exports = function (grunt) {
    grunt.config.merge({
        shell: {
            'tsc-types': {
                command: 'tsc -p tsconfig.types.json'
            }
        }
    });

    grunt.registerTask('build-types:clean', function () {
        fs.rmSync(OUT_DIR, { recursive: true, force: true });
        fs.mkdirSync(OUT_DIR, { recursive: true });
    });

    grunt.registerTask('build-types:scaffold-package', function () {
        const rootPkg = grunt.file.readJSON(path.join(REPO_ROOT, 'package.json'));

        const indexDts = `// Auto-generated by grunt build-types. Do not edit by hand.
import { FirebotPluginApi } from "./types/plugin-api";

export * from "./types";

declare const firebot: FirebotPluginApi;
export default firebot;
`;

        const indexJs = `// This package is a type-only shim. The real \`@crowbartools/firebot-types\` module is
// provided by the Firebot host at runtime via a require() interceptor.
throw new Error(
    "The '@crowbartools/firebot-types' module is only available when running inside Firebot."
);
`;

        const pkgJson = {
            name: '@crowbartools/firebot-types',
            version: rootPkg.version,
            description:
                'Type definitions and plugin API for Firebot plugins.',
            main: 'index.js',
            types: 'index.d.ts',
            exports: {
                '.': {
                    types: './index.d.ts',
                    default: './index.js'
                },
                './types': {
                    types: './types/index.d.ts'
                },
                './types/*': {
                    types: './types/*.d.ts'
                }
            },
            files: [
                'index.js',
                'index.d.ts',
                'types/**/*.d.ts',
                'backend/**/*.d.ts',
                'server/**/*.d.ts',
                'shared/**/*.d.ts',
                'README.md',
                'LICENSE'
            ],
            keywords: ['firebot', 'twitch', 'types', 'script', 'plugin'],
            repository: {
                type: 'git',
                url: 'git+https://github.com/crowbartools/Firebot.git'
            },
            homepage: 'https://firebot.app',
            bugs: 'https://github.com/crowbartools/Firebot/issues',
            author: rootPkg.author,
            license: rootPkg.license,
            peerDependencies: {
                '@types/express': '^5.0.5',
                '@types/node': '^24.1.0'
            },
            publishConfig: {
                access: "public"
            }
        };

        const readme = `# @crowbartools/firebot-types

Type definitions and the plugin API contract for [Firebot](https://firebot.app) plugins.

This package is **type-only**. At runtime the \`@crowbartools/firebot-types\` module is provided by the Firebot host application via a \`require()\` interceptor (installing this package in a standalone Node project and importing it will throw).

## Install

\`\`\`bash
npm i -D @crowbartools/firebot-types
\`\`\`

The following peer dependencies are required:
- \`@types/express\`
- \`@types/node\`

## Usage

The default export is the runtime API object provided by Firebot. Named types are re-exported from the package root and can be imported alongside the default in a single statement.

\`\`\`ts
import firebot, { Plugin } from "@crowbartools/firebot-types";

type Params = {
    message: string;
}

const plugin: Plugin<Params> = {
  manifest: {
    name: "My Plugin",
    version: "1.0.0",
    author: "you",
    description: "Example",
    type: "plugin"
  },
  parametersSchema: [
    {
      name: "message",
      type: "string",
      default: "Hello World!",
      title: "Hello!",
      description: "Message",
    }
  ],
  onLoad: (context) => {
    firebot.logger.info(\`\${context.parameters.message} (\${firebot.version})\`);
  }
}

export default plugin;
\`\`\`

CommonJS style works too (requires \`esModuleInterop\` in your tsconfig):

\`\`\`js
const firebot = require("@crowbartools/firebot-types").default;
firebot.logger.info(firebot.version);
\`\`\`

The version of this package tracks the Firebot version that produced it.
`;

        fs.writeFileSync(path.join(OUT_DIR, 'index.d.ts'), indexDts);
        fs.writeFileSync(path.join(OUT_DIR, 'index.js'), indexJs);
        fs.writeFileSync(
            path.join(OUT_DIR, 'package.json'),
            `${JSON.stringify(pkgJson, null, 2)}\n`
        );
        fs.writeFileSync(path.join(OUT_DIR, 'README.md'), readme);

        const licenseSrc = path.join(REPO_ROOT, 'license.txt');
        if (fs.existsSync(licenseSrc)) {
            fs.copyFileSync(licenseSrc, path.join(OUT_DIR, 'LICENSE'));
        }

        grunt.log.ok(`Scaffolded package files in ${OUT_DIR}`);
    });

    grunt.registerTask('build-types', [
        'build-types:clean',
        'shell:tsc-types',
        'build-types:scaffold-package'
    ]);
};
