'use strict';

const path = require('path');
const fs = require('fs');

const REPO_ROOT = path.join(__dirname, '..');
const SRC_TYPES = path.join(REPO_ROOT, 'src', 'types');
const OUT_DIR = path.join(REPO_ROOT, 'dist', 'types');
const OUT_TYPES = path.join(OUT_DIR, 'types');

function copyDtsTree(srcDir, destDir) {
    for (const entry of fs.readdirSync(srcDir, { withFileTypes: true })) {
        const srcPath = path.join(srcDir, entry.name);
        const destPath = path.join(destDir, entry.name);
        if (entry.isDirectory()) {
            fs.mkdirSync(destPath, { recursive: true });
            copyDtsTree(srcPath, destPath);
        } else if (entry.isFile() && entry.name.endsWith('.d.ts')) {
            fs.mkdirSync(path.dirname(destPath), { recursive: true });
            fs.copyFileSync(srcPath, destPath);
        }
    }
}

module.exports = function (grunt) {
    grunt.config.merge({
        shell: {
            'tsc-types': {
                command: 'tsc -p tsconfig.types.json'
            },
            'tsc-publish-deps': {
                // Emits .d.ts for the backend/shared trees so cross-tree
                // imports from src/types/*.d.ts (e.g. backend TwitchApi) resolve
                // inside the published package
                command: 'tsc -p tsconfig.publish-deps.json || true'
            }
        }
    });

    grunt.registerTask('publish-types:clean', function () {
        fs.rmSync(OUT_DIR, { recursive: true, force: true });
        fs.mkdirSync(OUT_TYPES, { recursive: true });
    });

    grunt.registerTask('publish-types:copy-dts', function () {
        copyDtsTree(SRC_TYPES, OUT_TYPES);
        grunt.log.ok(`Copied .d.ts files from ${SRC_TYPES} to ${OUT_TYPES}`);
    });

    grunt.registerTask('publish-types:write-shims', function () {
        const rootPkg = grunt.file.readJSON(path.join(REPO_ROOT, 'package.json'));

        const indexDts = `// Auto-generated by grunt publish-types. Do not edit by hand.
import { FirebotScriptApi } from "./types/script-api";

export * from "./types";

declare const firebot: FirebotScriptApi;
export default firebot;
`;

        const indexJs = `// This package is a type-only shim. The real \`@crowbartools/firebot-types\` module is
// provided by the Firebot host at runtime via a require() interceptor.
throw new Error(
    "The '@crowbartools/firebot-types' module is only available when running inside Firebot."
);
`;

        const pkgJson = {
            name: '@crowbartools/firebot-types',
            version: rootPkg.version,
            description:
                'Type definitions and script API for Firebot plugins and custom scripts.',
            main: 'index.js',
            types: 'index.d.ts',
            exports: {
                '.': {
                    types: './index.d.ts',
                    default: './index.js'
                },
                './types': {
                    types: './types/index.d.ts'
                },
                './types/*': {
                    types: './types/*.d.ts'
                }
            },
            files: [
                'index.js',
                'index.d.ts',
                'types/**/*.d.ts',
                'backend/**/*.d.ts',
                'server/**/*.d.ts',
                'shared/**/*.d.ts',
                'README.md',
                'LICENSE'
            ],
            keywords: ['firebot', 'twitch', 'types', 'script', 'plugin'],
            repository: {
                type: 'git',
                url: 'git+https://github.com/crowbartools/Firebot.git'
            },
            homepage: 'https://firebot.app',
            bugs: 'https://github.com/crowbartools/Firebot/issues',
            author: rootPkg.author,
            license: rootPkg.license,
            peerDependencies: {
                '@types/node': '*'
            },
            publishConfig: {
                access: "public"
            }
        };

        const readme = `# @crowbartools/firebot-types

Type definitions and the script API contract for [Firebot](https://firebot.app) custom scripts and plugins.

This package is **type-only**. At runtime the \`@crowbartools/firebot-types\` module is provided by the Firebot host application via a \`require()\` interceptor (installing this package in a standalone Node project and importing it will throw).

## Install

\`\`\`bash
npm i -D @crowbartools/firebot-types
\`\`\`

A \`@types/node\` peer dependency is required.

## Usage

The default export is the runtime API object provided by Firebot. Named types are re-exported from the package root and can be imported alongside the default in a single statement.

\`\`\`ts
import firebot, { Plugin } from "@crowbartools/firebot-types";

type Params = {
    message: string;
}

const plugin: Plugin<Params> = {
  manifest: {
    name: "My Plugin",
    version: "1.0.0",
    author: "you",
    description: "Example",
    type: "plugin"
  },
  parametersSchema: [
    {
      name: "message",
      type: "string",
      default: "Hello World!",
      title: "Hello!",
      description: "Message",
    }
  ],
  onLoad: (context) => {
    firebot.logger.info(\`\${context.parameters.message} (\${firebot.version})\`);
  }
}

export default plugin;
\`\`\`

CommonJS style works too (requires \`esModuleInterop\` in your tsconfig):

\`\`\`js
const firebot = require("@crowbartools/firebot-types").default;
firebot.logger.info(firebot.version);
\`\`\`

The version of this package tracks the Firebot version that produced it.
`;

        fs.writeFileSync(path.join(OUT_DIR, 'index.d.ts'), indexDts);
        fs.writeFileSync(path.join(OUT_DIR, 'index.js'), indexJs);
        fs.writeFileSync(
            path.join(OUT_DIR, 'package.json'),
            `${JSON.stringify(pkgJson, null, 2)}\n`
        );
        fs.writeFileSync(path.join(OUT_DIR, 'README.md'), readme);

        const licenseSrc = path.join(REPO_ROOT, 'license.txt');
        if (fs.existsSync(licenseSrc)) {
            fs.copyFileSync(licenseSrc, path.join(OUT_DIR, 'LICENSE'));
        }

        grunt.log.ok(`Wrote package shims to ${OUT_DIR}`);
    });

    grunt.registerTask('publish-types', [
        'publish-types:clean',
        'shell:tsc-publish-deps',
        'shell:tsc-types',
        'publish-types:copy-dts',
        'publish-types:write-shims'
    ]);
};
